services:
  frontend:
    container_name: b-saffer-frontend-staging
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./apps/frontend/Dockerfile
    networks:
      - proxy
    labels:
      - traefik.http.routers.frontend-staging.rule=Host(`${SERVER_DOMAIN}`)
      - traefik.http.routers.frontend-staging.tls=true
      - traefik.http.routers.frontend-staging.tls.certresolver=letsencrypt

  backend:
    command: cd apps/backend && npm run ci:dev
    container_name: b-saffer-backend-staging
    depends_on:
      postgres:
        condition: service_healthy
    build:
      context: .
      dockerfile: ./apps/backend/Dockerfile
    restart: unless-stopped
    environment:
      - DATABASE_URL=postgres://bsaffer:EqhvLbsPhrkkZjcaGWcV7qT@postgres:5432/bsaffer
    networks:
      - proxy
      - backend
    labels:
      - traefik.docker.network=traefik
      - traefik.http.routers.backend-staging.rule=Host(`${SERVER_DOMAIN}`) && PathPrefix(`/api`)
      - traefik.http.routers.backend-staging.tls=true
      - traefik.http.routers.backend-staging.tls.certresolver=letsencrypt
      - traefik.http.routers.backend-staging.middlewares=backend-stripprefix
      - traefik.http.services.backend-staging.loadbalancer.server.port=3000
      - traefik.http.middlewares.backend-stripprefix.stripprefix.prefixes=/api

  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: bsaffer
      POSTGRES_USER: bsaffer
      POSTGRES_PASSWORD: EqhvLbsPhrkkZjcaGWcV7qT
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "kc", "-U", "kc"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 60s
    networks:
      - backend

networks:
  proxy:
    external: true
    name: traefik
  backend:
