services:
  frontend:
    container_name: b-saffer-frontend
    restart: unless-stopped
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    networks:
      - proxy
    labels:
      - traefik.http.routers.frontend.rule=Host(`${SERVER_DOMAIN}`)
      - traefik.http.routers.frontend.tls=true
      - traefik.http.routers.frontend.tls.certresolver=letsencrypt

  backend:
    container_name: b-saffer-backend
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    restart: unless-stopped
    networks:
      - proxy
    labels:
      - traefik.http.routers.backend.rule=Host(`${SERVER_DOMAIN}`) && PathPrefix(`/api`)
      - traefik.http.routers.backend.tls=true
      - traefik.http.routers.backend.tls.certresolver=letsencrypt
      - traefik.http.services.backend.loadbalancer.server.port=3001

networks:
  proxy:
    external: true
    name: traefik
